### ISSUE TITLE
Request for Guidance on Robustness Testing in IDEAW Framework

### ISSUE THREAD

**Issue by xiaowenguo-hub** [PecholaL/IDEAW#3]
Hello, I am currently studying your work on the IDEAW framework, and I find it very insightful for audio watermarking research. I have been testing the provided implementation for embedding and extracting watermarks, and I aim to evaluate the robustness of the system under various audio attacks. Could you kindly provide guidance or share any sample code to perform robustness testing for the IDEAW framework? Thank you

**Comment by PecholaL** [comment]
Hi, thanks for your interest in IDEAW. 
As the previous tests were performed on an internal company server, I currently do not have the robustness evaluation code readily available to me. 
The robustness evaluation code is generally written following this process: 
audio+msg+l.code -(embedder)-> watermarked audio -(attack (e.g. attack in attack layer))-> attacked audio -(extractor)-> msg+l.code, then calculate the ACC of the extracted msg+l.code is extracted. 
Note that the applied attack can be any one of the attacks in the attack layer or a combination of multiple attacks, and the parameters of the attack can be different from those in the attack layer.

**Comment by wennyramadha** [comment]
> Hello, I am currently studying your work on the IDEAW framework, and I find it very insightful for audio watermarking research. I have been testing the provided implementation for embedding and extracting watermarks, and I aim to evaluate the robustness of the system under various audio attacks. Could you kindly provide guidance or share any sample code to perform robustness testing for the IDEAW framework? Thank you

Hi, do you mind sharing about which the dataset and how to use it for training? 

thank you

**Comment by PecholaL** [comment]
https://github.com/PecholaL/IDEAW/issues/4#issuecomment-2764420186
